create table if not exists public.monthly_summary_overrides (
  id bigint generated by default as identity not null,
  year_month character varying(7) not null,
  period character varying(16) not null,
  supplier_id bigint not null,
  price_per_qty_override numeric(12, 2) null,
  stimulation_override numeric(12, 2) null,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  constraint monthly_summary_overrides_pkey primary key (id),
  constraint monthly_summary_overrides_year_month_period_supplier_key unique (year_month, period, supplier_id),
  constraint monthly_summary_overrides_year_month_check check ((year_month ~ '^[0-9]{4}-[0-9]{2}$')),
  constraint monthly_summary_overrides_period_check check ((period)::text = any ((array['all'::character varying, 'first'::character varying, 'second'::character varying])::text[])),
  constraint monthly_summary_overrides_supplier_fkey foreign key (supplier_id) references public.suppliers (id) on delete cascade,
  constraint monthly_summary_overrides_any_value_check check (
    price_per_qty_override is not null
    or stimulation_override is not null
  )
) tablespace pg_default;

create index if not exists idx_monthly_summary_overrides_year_month_period
on public.monthly_summary_overrides using btree (year_month, period) tablespace pg_default;
